### ISSUE TITLE
Getting error message on initial setup 

### ISSUE THREAD

**Issue by danchristian** [entith/PugViewEngine#1]
Visual Studio 2015 / MVC 5.2.3 

I get an error message in `Global.asax.cs` after following the setup instructions:

`The type or namespace name 'PugViewEngine' could not be found (are you missing a using directive or an assembly reference?)`

I can see PugViewEngine in the `packages.config` folder. NPM Task Runner plugin is installed. 

What am I doing wrong?

**Comment by entith** [comment]
Sorry for the delayed response. Is `PugViewEngine` listed in a `<Reference>` tag in your `.csproj` file? You can also try closing Visual Studio, deleting the `bin` and `obj` directories in your project directory, and relaunching Visual Studio.

If you can upload the project source somewhere, I can download it and see whats going on. It'll be hard to troubleshoot further without seeing the issue in front of me.

**Comment by MaiklSemenov** [comment]
Just need to use ViewEngines.Engines.Add(new PugViewEngine());

**Comment by Majdzik** [comment]
Just add
```XML
<Reference Include="PugViewEngine">
      <Private>True</Private>
      <HintPath>..\packages\PugViewEngine.0.0.3.0\lib\net451\PugViewEngine.dll</HintPath>
 </Reference>
```
