### ISSUE TITLE
I cant see my view in my host

### ISSUE THREAD

**Issue by Asemxu** [entith/PugViewEngine#2]
Hi i need help i cant see my view in my host when a develop mi app 
i dont know if i need to configurated my web config for use .pug

**Comment by entith** [comment]
There is no `web.config` configuration needed. Have you followed the instructions in the [README](https://github.com/entith/PugViewEngine#setup)? Can you provide more details as to what your project setup looks like and what you've done so far?

**Comment by Asemxu** [comment]
yes in mi web config i donde do that anything, my proyect run well en IIS and localhost but when I deploy mi app in a hosting dont show me anything

[web_config.txt](https://github.com/entith/PugViewEngine/files/3895839/web_config.txt)
this is my web config

**Comment by Asemxu** [comment]
![image](https://user-images.githubusercontent.com/24592865/69706567-ff892080-10c5-11ea-9360-0fabf1b8f590.png)

**Comment by entith** [comment]
There is no `web.config` configuration needed.

What host are you publishing to? Are all the needed files making it to your publish location?
- `edge/*`
- `node_modules/*`
- `pugViewEngine.js`

Is your host perhaps blocking the execution of NodeJS?

**Comment by Asemxu** [comment]
> No se `web.config`necesita configuración.
> 
> ¿En qué host publicas? ¿Todos los archivos necesarios llegan a su ubicación de publicación?
> 
> * `edge/*`
> * `node_modules/*`
> * `pugViewEngine.js`
> 
> ¿Su host quizás está bloqueando la ejecución de NodeJS?
Nop , i have all packages , I installed with npm , in localhost my app run normally
but when i deploy o publish my app en my host i dont see views

**Comment by Asemxu** [comment]
But i dont know if my host is blocking my app

**Comment by entith** [comment]
When you publish to your host, are all the needed files being copied to the host?
- `edge/*`
- `node_modules/*`
- `pugViewEngine.js`

**Comment by Asemxu** [comment]
Yes I have all files, i test my app in dos host but in none working
![image](https://user-images.githubusercontent.com/24592865/69733639-a805a780-10fb-11ea-9f5e-8e819796f579.png)

**Comment by entith** [comment]
Is that on your host or your local machine?

**Comment by Asemxu** [comment]
in both

**Comment by Asemxu** [comment]
woo dont working this package for asp.net
